CREATE TABLE IF NOT EXISTS Utenti
(
	UserID INTEGER PRIMARY KEY AUTO_INCREMENT,
	User VARCHAR(50) NOT NULL,
	Pass VARCHAR(50) NOT NULL,
	Email VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS Linea
(
	IdLinea INTEGER PRIMARY KEY AUTO_INCREMENT,
    NomeLinea VARCHAR(5) NOT NULL,
    Direzione BIT(1) NOT NULL
);

CREATE TABLE IF NOT EXISTS Segnalazioni
(
	IdSegnalazione INTEGER PRIMARY KEY AUTO_INCREMENT,
	IdSegnalatore INTEGER NOT NULL,
	DataOra DATETIME NOT NULL,
    Linea INTEGER NOT NULL,
	Latitudine DECIMAL(10,8) NOT NULL,
    Longitudine DECIMAL(11,8) NOT NULL,
	FOREIGN KEY (IdSegnalatore) REFERENCES Utenti(UserID),
    FOREIGN KEY (Linea) REFERENCES Linea(IdLinea)
);

CREATE TABLE IF NOT EXISTS Fermata
(
	IdFermata INTEGER PRIMARY KEY AUTO_INCREMENT,
    NomeFermata VARCHAR(50),
	Latitudine DECIMAL(10,8) NOT NULL,
    Longitudine DECIMAL(11,8) NOT NULL,
    Direzione BIT(1) NOT NULL
);

CREATE TABLE IF NOT EXISTS Linea_Fermata
(
	IdLinea INTEGER AUTO_INCREMENT,
	IdFermata INTEGER NOT NULL,
	FOREIGN KEY (IdLinea) REFERENCES Linea(IdLinea),
	FOREIGN KEY (IdFermata) REFERENCES Fermata(IdFermata),
    primary key (IdLinea, IdFermata)
);

CREATE TABLE IF NOT EXISTS Corsa
(
	IdCorsa INTEGER PRIMARY KEY AUTO_INCREMENT,
	IdLinea INTEGER NOT NULL,
	FOREIGN KEY (IdLinea) REFERENCES Linea(IdLinea)
);

CREATE TABLE IF NOT EXISTS Corsa_Fermata_Orario
(
	IdCorsaFermataOrario INTEGER PRIMARY KEY AUTO_INCREMENT,
	IdCorsa INTEGER NOT NULL,
	IdLinea INTEGER NOT NULL,
	Orario TIME NOT NULL,
	IdFermata INTEGER NOT NULL,
	FOREIGN KEY (IdCorsa) REFERENCES Autobus(IdCorsa),
	FOREIGN KEY (IdLinea) REFERENCES Autobus(IdLinea),
	FOREIGN KEY (IdFermata) REFERENCES Fermata(IdFermata)
);

CREATE TABLE IF NOT EXISTS Ritardi
(
	IdRitardo INTEGER PRIMARY KEY AUTO_INCREMENT,
	IdCorsaFermataOrario INTEGER NOT NULL,
	Ritardo TIME NOT NULL,
	FOREIGN KEY (IdAutobusFermataOrario) REFERENCES Autobus_Fermata_Orario(IdAutobusFermataOrario)
);