use ritardoautobus;

DROP TABLE IF EXISTS Ritardo;
DROP TABLE IF EXISTS Corsa_Fermata_Orario;
DROP TABLE IF EXISTS Linea_Fermata;
DROP TABLE IF EXISTS Segnalazione;
DROP TABLE IF EXISTS Corsa;
DROP TABLE IF EXISTS Fermata;
DROP TABLE IF EXISTS Linea;
DROP TABLE IF EXISTS Utenti_Hit_Id;
DROP TABLE IF EXISTS Utente;
