use ritardoautobus;

DROP TABLE IF EXISTS Ritardi;
DROP TABLE IF EXISTS Corsa_Fermata_Orario;
DROP TABLE IF EXISTS Linea_Fermata;
DROP TABLE IF EXISTS Segnalazioni;
DROP TABLE IF EXISTS Corsa;
DROP TABLE IF EXISTS Fermata;
DROP TABLE IF EXISTS Linea;
DROP TABLE IF EXISTS Utenti;